### ISSUE TITLE
: Error: Error when reading 'lib/gitkey.dart': No such file or directory import 'package:Prism/gitkey.dart';

### ISSUE THREAD

**Issue by jinfagang** [Hash-Studios/Prism#51]
: Error: Error when reading 'lib/gitkey.dart': No such
file or directory
import 'package:Prism/gitkey.dart';

**Comment by codenameakshay** [comment]
We have updated our contribution guidelines now, [Contributing.md](https://github.com/Hash-Studios/Prism/blob/master/CONTRIBUTING.md) and you can check out here how to create gitkey.dart
Make sure to add gitkey to your .gitignore file, so that the repo remains confidential.

------------------------------------------------------------------------
From Contributing.md

2. You need to create a file called gitkey.dart with the following syntax that stores the username and password for the GitHub Repository where you want to save your uploaded wallpapers.
```
const String username = 'username'
const String password = 'password'
```
